debug: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goo?useUnicode=true&characterEncoding=utf8
    username: tester
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.exercise.mybatis.v1
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    default-executor-type: simple
    default-statement-timeout: 30