package com.sununiq.scaffold.domain;

import java.util.Date;

public class DeptManager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_manager.emp_no
     *
     * @mbg.generated
     */
    private Integer empNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_manager.dept_no
     *
     * @mbg.generated
     */
    private String deptNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_manager.from_date
     *
     * @mbg.generated
     */
    private Date fromDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_manager.to_date
     *
     * @mbg.generated
     */
    private Date toDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_manager.emp_no
     *
     * @return the value of dept_manager.emp_no
     *
     * @mbg.generated
     */
    public Integer getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_manager.emp_no
     *
     * @param empNo the value for dept_manager.emp_no
     *
     * @mbg.generated
     */
    public void setEmpNo(Integer empNo) {
        this.empNo = empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_manager.dept_no
     *
     * @return the value of dept_manager.dept_no
     *
     * @mbg.generated
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_manager.dept_no
     *
     * @param deptNo the value for dept_manager.dept_no
     *
     * @mbg.generated
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo == null ? null : deptNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_manager.from_date
     *
     * @return the value of dept_manager.from_date
     *
     * @mbg.generated
     */
    public Date getFromDate() {
        return fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_manager.from_date
     *
     * @param fromDate the value for dept_manager.from_date
     *
     * @mbg.generated
     */
    public void setFromDate(Date fromDate) {
        this.fromDate = fromDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_manager.to_date
     *
     * @return the value of dept_manager.to_date
     *
     * @mbg.generated
     */
    public Date getToDate() {
        return toDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_manager.to_date
     *
     * @param toDate the value for dept_manager.to_date
     *
     * @mbg.generated
     */
    public void setToDate(Date toDate) {
        this.toDate = toDate;
    }
}