package com.sununiq.scaffold.dao;

import com.sununiq.scaffold.domain.CurrentDeptEmp;
import java.util.List;

public interface CurrentDeptEmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table current_dept_emp
     *
     * @mbg.generated
     */
    int insert(CurrentDeptEmp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table current_dept_emp
     *
     * @mbg.generated
     */
    List<CurrentDeptEmp> selectAll();
}