package com.sununiq.scaffold.dao;

import com.sununiq.scaffold.domain.DeptEmpLatestDate;
import java.util.List;

public interface DeptEmpLatestDateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp_latest_date
     *
     * @mbg.generated
     */
    int insert(DeptEmpLatestDate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_emp_latest_date
     *
     * @mbg.generated
     */
    List<DeptEmpLatestDate> selectAll();
}