package com.sununiq.scaffold.dao;

import com.sununiq.scaffold.domain.Titles;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TitlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("empNo") Integer empNo, @Param("title") String title, @Param("fromDate") Date fromDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    int insert(Titles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    Titles selectByPrimaryKey(@Param("empNo") Integer empNo, @Param("title") String title, @Param("fromDate") Date fromDate);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    List<Titles> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table titles
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Titles record);
}